In [1]:
#Aim is to make a API web crawler from provided link 
#Then input functions as per the requirements
#create a database using mysql and then 
#put the data into the database 
#Add other components like logging and testing into the database

## Problem statement

#### Evaluation Criteria 

- Solution to a problem
- Appropriate Variable names
- Appropriate Error Handling
- Logs
- Appropriate comments
- Optimized Solution. Maximum use of inbuilt functions.
- Reusability of code.

Consume -  https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&apikey=NQCFKOVGZASY3EZ9&symbol=MSFT
 
Where symbol = MSFT is company name and is configurable.
Below are few example of company names - 
1) MSFT<br>
2) ABB<br>
3) AAL            AMERICAN AIRLINES GROUP INC<br>
4) AAPL            APPLE INC<br>
5) DELL            DELL TECHNOLOGIES INC<br>
 
 
This API will return Time Series data per date of given company. 
 
- function which will crawl this API which returns json output and insert into database per company, per date data of all 8 factors.
 
#### Perform below operations on already consumed data -

- function which return all opening, closing, high, low for given company and date, also write this output to csv and json file.

- function which will return per date difference between closing and opening value of a given company.

- function which will calculate per date average of all companies' difference between closing and opening value.

- function which will return maximum number of continuous days where closing value was greater than opening value(where trend is positive) for a given company.

In [1]:
#import libraries
import urllib , json , requests
import pandas as pd
import sqlite3
from sqlite3 import Error

In [1]:
arr=['MSFT','ABB','AAL','AAPL','DELL']

In [2]:
#get all the uRL's from where we have to fetch data 
def getURL(arr):
    urlList=[]
    for company in arr:
        url=f"https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED\
        &apikey=NQCFKOVGZASY3EZ9&symbol={company}"
        url = url.replace(" ","") #in case there is any space in URL 
        urlList.append(url)
    return urlList

In [3]:
#imports json from the api 
def ImportJson(url):
    response =urllib.request.urlopen(url)
    data=json.loads(response.read()) #converts to python dict 
    return data

In [22]:
#other method could be using json decoder 
# url="https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&apikey=NQCFKOVGZASY3EZ9&symbol=MSFT"
# r = requests.get(url)
# print(f'{r.json()}')

In [35]:
data=ImportJson(getURL(arr)[1])

In [39]:
data

{'Meta Data': {'1. Information': 'Daily Time Series with Splits and Dividend Events',
  '2. Symbol': 'ABB',
  '3. Last Refreshed': '2021-06-23',
  '4. Output Size': 'Compact',
  '5. Time Zone': 'US/Eastern'},
 'Time Series (Daily)': {'2021-06-23': {'1. open': '34.0',
   '2. high': '34.085',
   '3. low': '33.7',
   '4. close': '33.7',
   '5. adjusted close': '33.7',
   '6. volume': '1100367',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-06-22': {'1. open': '33.65',
   '2. high': '33.95',
   '3. low': '33.53',
   '4. close': '33.84',
   '5. adjusted close': '33.84',
   '6. volume': '1462695',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-06-21': {'1. open': '33.36',
   '2. high': '33.78',
   '3. low': '33.3',
   '4. close': '33.74',
   '5. adjusted close': '33.74',
   '6. volume': '1111415',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-06-18': {'1. open': '33.07',
   '2. high': '33.15',
   '3. low': '32.8',
   '4. close': '32.81',
   '5. adjusted close': '32.81',
   '6. volume': '1818911',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-06-17': {'1. open': '33.68',
   '2. high': '33.78',
   '3. low': '33.2',
   '4. close': '33.45',
   '5. adjusted close': '33.45',
   '6. volume': '1483827',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-06-16': {'1. open': '34.64',
   '2. high': '34.65',
   '3. low': '33.95',
   '4. close': '34.06',
   '5. adjusted close': '34.06',
   '6. volume': '1497225',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-06-15': {'1. open': '34.78',
   '2. high': '34.915',
   '3. low': '34.735',
   '4. close': '34.82',
   '5. adjusted close': '34.82',
   '6. volume': '1159560',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-06-14': {'1. open': '34.54',
   '2. high': '34.63',
   '3. low': '34.385',
   '4. close': '34.63',
   '5. adjusted close': '34.63',
   '6. volume': '1231269',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-06-11': {'1. open': '34.6',
   '2. high': '34.65',
   '3. low': '34.45',
   '4. close': '34.55',
   '5. adjusted close': '34.55',
   '6. volume': '987131',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-06-10': {'1. open': '34.61',
   '2. high': '34.735',
   '3. low': '34.55',
   '4. close': '34.63',
   '5. adjusted close': '34.63',
   '6. volume': '1135211',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-06-09': {'1. open': '34.86',
   '2. high': '34.87',
   '3. low': '34.67',
   '4. close': '34.73',
   '5. adjusted close': '34.73',
   '6. volume': '917783',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-06-08': {'1. open': '35.11',
   '2. high': '35.13',
   '3. low': '34.89',
   '4. close': '35.03',
   '5. adjusted close': '35.03',
   '6. volume': '1061946',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-06-07': {'1. open': '35.28',
   '2. high': '35.28',
   '3. low': '35.04',
   '4. close': '35.17',
   '5. adjusted close': '35.17',
   '6. volume': '821513',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-06-04': {'1. open': '35.0',
   '2. high': '35.135',
   '3. low': '34.91',
   '4. close': '35.1',
   '5. adjusted close': '35.1',
   '6. volume': '674567',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-06-03': {'1. open': '34.6',
   '2. high': '34.73',
   '3. low': '34.4',
   '4. close': '34.63',
   '5. adjusted close': '34.63',
   '6. volume': '805990',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-06-02': {'1. open': '34.73',
   '2. high': '34.92',
   '3. low': '34.65',
   '4. close': '34.78',
   '5. adjusted close': '34.78',
   '6. volume': '1012179',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-06-01': {'1. open': '34.84',
   '2. high': '34.87',
   '3. low': '34.665',
   '4. close': '34.71',
   '5. adjusted close': '34.71',
   '6. volume': '1052620',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-05-28': {'1. open': '34.07',
   '2. high': '34.25',
   '3. low': '34.04',
   '4. close': '34.14',
   '5. adjusted close': '34.14',
   '6. volume': '1554616',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-05-27': {'1. open': '33.93',
   '2. high': '34.2',
   '3. low': '33.92',
   '4. close': '34.16',
   '5. adjusted close': '34.16',
   '6. volume': '2678012',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-05-26': {'1. open': '33.61',
   '2. high': '33.82',
   '3. low': '33.58',
   '4. close': '33.77',
   '5. adjusted close': '33.77',
   '6. volume': '2083601',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-05-25': {'1. open': '33.83',
   '2. high': '33.945',
   '3. low': '33.6249',
   '4. close': '33.67',
   '5. adjusted close': '33.67',
   '6. volume': '1296949',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-05-24': {'1. open': '33.54',
   '2. high': '33.83',
   '3. low': '33.5',
   '4. close': '33.75',
   '5. adjusted close': '33.75',
   '6. volume': '929419',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-05-21': {'1. open': '33.6',
   '2. high': '33.73',
   '3. low': '33.45',
   '4. close': '33.65',
   '5. adjusted close': '33.65',
   '6. volume': '1132356',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-05-20': {'1. open': '33.14',
   '2. high': '33.4',
   '3. low': '33.11',
   '4. close': '33.33',
   '5. adjusted close': '33.33',
   '6. volume': '918249',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-05-19': {'1. open': '32.81',
   '2. high': '33.105',
   '3. low': '32.575',
   '4. close': '32.94',
   '5. adjusted close': '32.94',
   '6. volume': '1727646',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-05-18': {'1. open': '34.16',
   '2. high': '34.17',
   '3. low': '33.83',
   '4. close': '33.84',
   '5. adjusted close': '33.84',
   '6. volume': '2413212',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-05-17': {'1. open': '33.86',
   '2. high': '33.9653',
   '3. low': '33.683',
   '4. close': '33.83',
   '5. adjusted close': '33.83',
   '6. volume': '2041107',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-05-14': {'1. open': '33.85',
   '2. high': '34.32',
   '3. low': '33.785',
   '4. close': '34.22',
   '5. adjusted close': '34.22',
   '6. volume': '1656300',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-05-13': {'1. open': '32.74',
   '2. high': '33.37',
   '3. low': '32.73',
   '4. close': '33.26',
   '5. adjusted close': '33.26',
   '6. volume': '1273038',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-05-12': {'1. open': '33.02',
   '2. high': '33.175',
   '3. low': '32.511',
   '4. close': '32.57',
   '5. adjusted close': '32.57',
   '6. volume': '1413854',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-05-11': {'1. open': '33.1',
   '2. high': '33.42',
   '3. low': '32.97',
   '4. close': '33.38',
   '5. adjusted close': '33.38',
   '6. volume': '1389772',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-05-10': {'1. open': '33.86',
   '2. high': '33.88',
   '3. low': '33.5',
   '4. close': '33.51',
   '5. adjusted close': '33.51',
   '6. volume': '1130698',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-05-07': {'1. open': '33.87',
   '2. high': '34.175',
   '3. low': '33.73',
   '4. close': '34.11',
   '5. adjusted close': '34.11',
   '6. volume': '972339',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-05-06': {'1. open': '33.62',
   '2. high': '33.78',
   '3. low': '33.43',
   '4. close': '33.77',
   '5. adjusted close': '33.77',
   '6. volume': '1219821',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-05-05': {'1. open': '33.46',
   '2. high': '33.69',
   '3. low': '33.28',
   '4. close': '33.51',
   '5. adjusted close': '33.51',
   '6. volume': '2613000',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-05-04': {'1. open': '32.46',
   '2. high': '32.66',
   '3. low': '32.295',
   '4. close': '32.66',
   '5. adjusted close': '32.66',
   '6. volume': '1637804',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-05-03': {'1. open': '32.85',
   '2. high': '32.9681',
   '3. low': '32.81',
   '4. close': '32.89',
   '5. adjusted close': '32.89',
   '6. volume': '775374',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-04-30': {'1. open': '32.71',
   '2. high': '32.85',
   '3. low': '32.405',
   '4. close': '32.43',
   '5. adjusted close': '32.43',
   '6. volume': '1151552',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-04-29': {'1. open': '33.37',
   '2. high': '33.4',
   '3. low': '32.94',
   '4. close': '33.24',
   '5. adjusted close': '33.24',
   '6. volume': '934499',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-04-28': {'1. open': '33.21',
   '2. high': '33.41',
   '3. low': '33.175',
   '4. close': '33.29',
   '5. adjusted close': '33.29',
   '6. volume': '1274304',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-04-27': {'1. open': '33.12',
   '2. high': '33.19',
   '3. low': '32.93',
   '4. close': '33.06',
   '5. adjusted close': '33.06',
   '6. volume': '1101957',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-04-26': {'1. open': '32.65',
   '2. high': '32.77',
   '3. low': '32.59',
   '4. close': '32.75',
   '5. adjusted close': '32.75',
   '6. volume': '1236810',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-04-23': {'1. open': '32.46',
   '2. high': '32.85',
   '3. low': '32.435',
   '4. close': '32.77',
   '5. adjusted close': '32.77',
   '6. volume': '1007910',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-04-22': {'1. open': '32.54',
   '2. high': '32.56',
   '3. low': '32.245',
   '4. close': '32.32',
   '5. adjusted close': '32.32',
   '6. volume': '1821909',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-04-21': {'1. open': '32.28',
   '2. high': '32.75',
   '3. low': '32.19',
   '4. close': '32.74',
   '5. adjusted close': '32.74',
   '6. volume': '1280925',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-04-20': {'1. open': '32.97',
   '2. high': '33.015',
   '3. low': '32.455',
   '4. close': '32.59',
   '5. adjusted close': '32.59',
   '6. volume': '1080797',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-04-19': {'1. open': '33.43',
   '2. high': '33.44',
   '3. low': '33.07',
   '4. close': '33.24',
   '5. adjusted close': '33.24',
   '6. volume': '1322847',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-04-16': {'1. open': '33.27',
   '2. high': '33.48',
   '3. low': '33.15',
   '4. close': '33.38',
   '5. adjusted close': '33.38',
   '6. volume': '1478293',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-04-15': {'1. open': '32.71',
   '2. high': '32.95',
   '3. low': '32.59',
   '4. close': '32.93',
   '5. adjusted close': '32.93',
   '6. volume': '1455394',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-04-14': {'1. open': '31.67',
   '2. high': '31.8',
   '3. low': '31.56',
   '4. close': '31.59',
   '5. adjusted close': '31.59',
   '6. volume': '940441',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-04-13': {'1. open': '31.57',
   '2. high': '31.74',
   '3. low': '31.42',
   '4. close': '31.7',
   '5. adjusted close': '31.7',
   '6. volume': '994967',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-04-12': {'1. open': '31.71',
   '2. high': '31.8171',
   '3. low': '31.65',
   '4. close': '31.77',
   '5. adjusted close': '31.77',
   '6. volume': '847065',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-04-09': {'1. open': '31.78',
   '2. high': '32.095',
   '3. low': '31.77',
   '4. close': '32.08',
   '5. adjusted close': '32.08',
   '6. volume': '978326',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-04-08': {'1. open': '31.58',
   '2. high': '31.6',
   '3. low': '31.4',
   '4. close': '31.58',
   '5. adjusted close': '31.58',
   '6. volume': '1700609',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-04-07': {'1. open': '31.31',
   '2. high': '31.36',
   '3. low': '31.0839',
   '4. close': '31.21',
   '5. adjusted close': '31.21',
   '6. volume': '1436268',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-04-06': {'1. open': '31.24',
   '2. high': '31.42',
   '3. low': '31.14',
   '4. close': '31.16',
   '5. adjusted close': '31.16',
   '6. volume': '1780514',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-04-05': {'1. open': '30.91',
   '2. high': '31.52',
   '3. low': '30.74',
   '4. close': '31.32',
   '5. adjusted close': '31.32',
   '6. volume': '1326888',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-04-01': {'1. open': '30.49',
   '2. high': '30.71',
   '3. low': '30.425',
   '4. close': '30.66',
   '5. adjusted close': '30.66',
   '6. volume': '1351664',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-03-31': {'1. open': '30.41',
   '2. high': '30.57',
   '3. low': '30.3031',
   '4. close': '30.47',
   '5. adjusted close': '30.47',
   '6. volume': '1964450',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-03-30': {'1. open': '30.09',
   '2. high': '30.31',
   '3. low': '30.07',
   '4. close': '30.22',
   '5. adjusted close': '30.22',
   '6. volume': '1153685',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-03-29': {'1. open': '30.29',
   '2. high': '30.49',
   '3. low': '30.19',
   '4. close': '30.32',
   '5. adjusted close': '30.32',
   '6. volume': '1805660',
   '7. dividend amount': '0.8743',
   '8. split coefficient': '1.0'},
  '2021-03-26': {'1. open': '31.18',
   '2. high': '31.59',
   '3. low': '31.13',
   '4. close': '31.59',
   '5. adjusted close': '30.7045937471',
   '6. volume': '1876287',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-03-25': {'1. open': '30.68',
   '2. high': '31.105',
   '3. low': '30.35',
   '4. close': '31.08',
   '5. adjusted close': '30.2088880551',
   '6. volume': '2011250',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-03-24': {'1. open': '30.99',
   '2. high': '31.11',
   '3. low': '30.825',
   '4. close': '30.85',
   '5. adjusted close': '29.9853345077',
   '6. volume': '1408286',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-03-23': {'1. open': '31.52',
   '2. high': '31.66',
   '3. low': '31.03',
   '4. close': '31.03',
   '5. adjusted close': '30.1602894579',
   '6. volume': '2546713',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-03-22': {'1. open': '31.41',
   '2. high': '31.75',
   '3. low': '31.38',
   '4. close': '31.56',
   '5. adjusted close': '30.6754345888',
   '6. volume': '1907783',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-03-19': {'1. open': '30.88',
   '2. high': '31.455',
   '3. low': '30.74',
   '4. close': '31.36',
   '5. adjusted close': '30.4810401998',
   '6. volume': '2822906',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-03-18': {'1. open': '31.11',
   '2. high': '31.3',
   '3. low': '30.835',
   '4. close': '30.85',
   '5. adjusted close': '29.9853345077',
   '6. volume': '1610027',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-03-17': {'1. open': '30.73',
   '2. high': '31.04',
   '3. low': '30.615',
   '4. close': '31.02',
   '5. adjusted close': '30.1505697384',
   '6. volume': '1002148',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-03-16': {'1. open': '31.05',
   '2. high': '31.08',
   '3. low': '30.84',
   '4. close': '30.92',
   '5. adjusted close': '30.0533725439',
   '6. volume': '1398214',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-03-15': {'1. open': '30.73',
   '2. high': '31.165',
   '3. low': '30.53',
   '4. close': '31.1',
   '5. adjusted close': '30.228327494',
   '6. volume': '2517532',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-03-12': {'1. open': '30.53',
   '2. high': '30.79',
   '3. low': '30.51',
   '4. close': '30.79',
   '5. adjusted close': '29.927016191',
   '6. volume': '1260728',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-03-11': {'1. open': '30.83',
   '2. high': '31.14',
   '3. low': '30.735',
   '4. close': '30.89',
   '5. adjusted close': '30.0242133855',
   '6. volume': '1478115',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-03-10': {'1. open': '30.55',
   '2. high': '30.765',
   '3. low': '30.38',
   '4. close': '30.72',
   '5. adjusted close': '29.8589781549',
   '6. volume': '1832354',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-03-09': {'1. open': '30.19',
   '2. high': '30.5999',
   '3. low': '30.11',
   '4. close': '30.44',
   '5. adjusted close': '29.5868260102',
   '6. volume': '1339643',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-03-08': {'1. open': '29.93',
   '2. high': '30.37',
   '3. low': '29.87',
   '4. close': '30.0',
   '5. adjusted close': '29.1591583544',
   '6. volume': '2058896',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-03-05': {'1. open': '29.43',
   '2. high': '29.775',
   '3. low': '28.93',
   '4. close': '29.7',
   '5. adjusted close': '28.8675667708',
   '6. volume': '3284830',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-03-04': {'1. open': '29.71',
   '2. high': '29.785',
   '3. low': '28.66',
   '4. close': '29.17',
   '5. adjusted close': '28.3524216399',
   '6. volume': '4105029',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-03-03': {'1. open': '29.62',
   '2. high': '29.745',
   '3. low': '29.37',
   '4. close': '29.42',
   '5. adjusted close': '28.5954146262',
   '6. volume': '1348632',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-03-02': {'1. open': '29.82',
   '2. high': '29.89',
   '3. low': '29.54',
   '4. close': '29.77',
   '5. adjusted close': '28.935604807',
   '6. volume': '1625927',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-03-01': {'1. open': '29.25',
   '2. high': '29.5',
   '3. low': '29.23',
   '4. close': '29.28',
   '5. adjusted close': '28.4593385539',
   '6. volume': '1539677',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-02-26': {'1. open': '29.1',
   '2. high': '29.11',
   '3. low': '28.72',
   '4. close': '28.78',
   '5. adjusted close': '27.9733525813',
   '6. volume': '1850066',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},
  '2021-02-25': {'1. open': '29.73',
   '2. high': '29.85',
   '3. low': '29.18',
   '4. close': '29.28',
   '5. adjusted close': '28.4593385539',
   '6. volume': '1567589',
   '7. dividend amount': '0.0000',
   '8. split coefficient': '1.0'},

In [47]:
# dates=[]
# for item in data['Time Series (Daily)']:
#     dates.append(str(item))
# print(len(dates))

100

In [ ]:
#we can kind of convert it into a class

In [130]:
res=[]
for item in data['Time Series (Daily)'].items():
    cateogary=list(item)
    res.append(cateogary)

[['2021-06-23', {'1. open': '34.0', '2. high': '34.085', '3. low': '33.7', '4. close': '33.7', '5. adjusted close': '33.7', '6. volume': '1100367', '7. dividend amount': '0.0000', '8. split coefficient': '1.0'}], ['2021-06-22', {'1. open': '33.65', '2. high': '33.95', '3. low': '33.53', '4. close': '33.84', '5. adjusted close': '33.84', '6. volume': '1462695', '7. dividend amount': '0.0000', '8. split coefficient': '1.0'}]]

In [131]:
#this one
dates=[]
Open = []
high = []
low =  []
close =[]
adjusted_close = []
volume = []
dividend_amount = []
split_coefficient =[]

for date, d in res:
    dates.append(date)
    Open.append(d['1. open'])
    high.append(d['2. high'])
    low.append(d['3. low'])
    close.append(d['4. close'])
    adjusted_close.append(d['5. adjusted close'])
    volume.append(d['6. volume'])
    dividend_amount.append(d['7. dividend amount'])
    split_coefficient.append(d['8. split coefficient'])

['0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.8743', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000', '0.0000']

In [125]:
#for op,hi,lo,cl,ac,vol,div,split in list(item):
#  open = 34.0
#  high = 34.085
#  low = 33.7
#  close = 33.7
#  adjusted close = 33.7
#  volume = 1100367
#  dividend amount = 0.0000
#  split coefficient

In [132]:
# res=[]
# for items in data['Time Series (Daily)'].values():
#     res.append(list(items.items()))
# for index in res:
#     for product,value in index:
#         individual_list.append((print(f"{product[2:]} = {value}")

In [141]:
#establish connection

In [21]:
# def create_connection(db_file):
#     """ create a database connection to a SQLite database """
#     conn = None
#     try:
#         conn = sqlite3.connect(db_file)
#         print(conn)
#     except Error as e:
#         print(e)
#     finally:
#         if conn:
#             conn.close()

In [22]:
#we made a folder a folder db with parent as sqlite and created a db
# create_connection(r"C:\Users\saksham.gupta\sqlite\db\pythonsqlite.db")

In [23]:
def create_connection(db_file):
    conn=None
    try:
        conn = sqlite3.connect(db_file)
        return conn
    except Error as e:
        print(e)
    return conn

In [24]:
# create_connection(r"C:\Users\saksham.gupta\sqlite\db\pythonsqlite.db")

In [43]:
database=r"C:\Users\saksham.gupta\sqlite\db\pythonsqlite.db"

In [26]:
def create_table(conn, create_table_sql):
    """ create a table from the create_table_sql statement"""
    try:
        c = conn.cursor()
        c.execute(create_table_sql)
    except Error as e:
        print(e)

In [44]:
#create table 
sql_create_projects_table = """ CREATE TABLE IF NOT EXISTS shares (
                                company_name TEXT NOT NULL,
                                dates TEXT NOT NULL,
                                Open REAL , 
                                high  REAL ,
                                low  REAL ,
                                close  REAL ,
                                adjusted_close  REAL ,
                                volume REAL ,
                                dividend_amount  REAL ,
                                split_coefficient  REAL); """

# create a database connection
conn = create_connection(database)

# create tables
if conn is not None:
    # create projects table
    create_table(conn, sql_create_projects_table)

else:
    print("Error! cannot create the database connection.")

In [45]:
cursor=conn.cursor()

In [46]:
data=ImportJson(getURL(arr)[1])

In [47]:
company_name=arr[1]
company_name

'ABB'

In [48]:
#saving the whole comapny data into list 
res=[]
for item in data['Time Series (Daily)'].items():
    cateogary=list(item)
    res.append(cateogary)

In [49]:
#initialize variables
dates=0
Open = 0
high = 0
low = 0
close =0 
adjusted_close =0 
volume=0
dividend_amount = 0
split_coefficient=0

In [50]:
#insert data rows into shares
for date, d in res:
    dates=date
    Open=d['1. open']
    high=d['2. high']
    low=d['3. low']
    close=d['4. close']
    adjusted_closed=d['5. adjusted close']
    volume=d['6. volume']
    dividend_amount=d['7. dividend amount']
    split_coefficient=d['8. split coefficient']
    
    cursor.execute("INSERT INTO shares VALUES (?,?,?,?,?,?,?,?,?,?)",(company_name,dates,Open,high,low,
                                                                      close,adjusted_close,volume,
                                                                      dividend_amount,split_coefficient))

In [57]:
conn.commit()

In [56]:
count=0
for row in cursor.execute('SELECT * FROM shares;'):
    count+=1
    print(row)
    if count>5:
        break

('ABB', '2021-06-24', 33.79, 34.3677, 33.72, 34.3, 0.0, 1872907.0, 0.0, 1.0)
('ABB', '2021-06-23', 34.0, 34.085, 33.7, 33.7, 0.0, 1100367.0, 0.0, 1.0)
('ABB', '2021-06-22', 33.65, 33.95, 33.53, 33.84, 0.0, 1462695.0, 0.0, 1.0)
('ABB', '2021-06-21', 33.36, 33.78, 33.3, 33.74, 0.0, 1111415.0, 0.0, 1.0)
('ABB', '2021-06-18', 33.07, 33.15, 32.8, 32.81, 0.0, 1818911.0, 0.0, 1.0)
('ABB', '2021-06-17', 33.68, 33.78, 33.2, 33.45, 0.0, 1483827.0, 0.0, 1.0)

In [ ]:
#works 
#1st function using variable 
# def getFearture():
cursor.execute('SELECT Open ,high , low , close FROM shares WHERE company_name = ?', (company,))
cursor.fetchall()

In [128]:
columns=['company_name','dates','Open','high','low','close','adjusted_close',
         'volume','dividend_amount','split_coefficient']
labels=['Open','high','low','close']

In [129]:
company_name= '"ABB"'
print(company_name)

"ABB"

In [130]:
query="SELECT Open ,high , low , close FROM shares WHERE company_name = " + company_name
df =pd.read_sql_query(query,conn)

# df.to_csv('features.csv',columns=columns,header=False, index=False)

In [131]:
df.to_csv('new_features.csv',columns=labels, index=False)

In [ ]:
#enter data into database
def EnterData():

In [ ]:
#checking if file is already present in the location 
import glob
import pandas as pd

# Give the filename you wish to save the file to
filename = 'Your_filename.csv'

# Use this function to search for any files which match your filename
files_present = glob.glob(filename)


# if no matching files, write to csv, if there are matching files, print statement
if not files_present:
    pd.to_csv(filename)
else:
    print 'WARNING: This file already exists!'

In [2]:
#driver code (connecting and executing query)
database=r"C:\Users\saksham.gupta\sqlite\db\pythonsqlite.db"
conn=sqlite3.connect(database)
cursor=conn.cursor()

In [88]:
company_name= '"ABB"' # format of putting variable in sql
query="SELECT low, Open , high , close FROM shares WHERE company_name=" + company_name
result=cursor.execute(query)

In [89]:
for key in cursor.description:
    print(key[0])

low
Open
high
close

In [90]:
#1st question part 2 
#great method I loved it , simplifies form 
features=[dict(zip([key[0] for key in cursor.description], row)) for row in result]
print(json.dumps({'features':features},indent=2))

{
  "features": [
    {
      "low": 33.72,
      "Open": 33.79,
      "high": 34.3677,
      "close": 34.3
    },
    {
      "low": 33.7,
      "Open": 34.0,
      "high": 34.085,
      "close": 33.7
    },
    {
      "low": 33.53,
      "Open": 33.65,
      "high": 33.95,
      "close": 33.84
    },
    {
      "low": 33.3,
      "Open": 33.36,
      "high": 33.78,
      "close": 33.74
    },
    {
      "low": 32.8,
      "Open": 33.07,
      "high": 33.15,
      "close": 32.81
    },
    {
      "low": 33.2,
      "Open": 33.68,
      "high": 33.78,
      "close": 33.45
    },
    {
      "low": 33.95,
      "Open": 34.64,
      "high": 34.65,
      "close": 34.06
    },
    {
      "low": 34.735,
      "Open": 34.78,
      "high": 34.915,
      "close": 34.82
    },
    {
      "low": 34.385,
      "Open": 34.54,
      "high": 34.63,
      "close": 34.63
    },
    {
      "low": 34.45,
      "Open": 34.6,
      "high": 34.65,
      "close": 34.55
    },
    {
      "low": 34.55,
      "Open": 34.61,
      "high": 34.735,
      "close": 34.63
    },
    {
      "low": 34.67,
      "Open": 34.86,
      "high": 34.87,
      "close": 34.73
    },
    {
      "low": 34.89,
      "Open": 35.11,
      "high": 35.13,
      "close": 35.03
    },
    {
      "low": 35.04,
      "Open": 35.28,
      "high": 35.28,
      "close": 35.17
    },
    {
      "low": 34.91,
      "Open": 35.0,
      "high": 35.135,
      "close": 35.1
    },
    {
      "low": 34.4,
      "Open": 34.6,
      "high": 34.73,
      "close": 34.63
    },
    {
      "low": 34.65,
      "Open": 34.73,
      "high": 34.92,
      "close": 34.78
    },
    {
      "low": 34.665,
      "Open": 34.84,
      "high": 34.87,
      "close": 34.71
    },
    {
      "low": 34.04,
      "Open": 34.07,
      "high": 34.25,
      "close": 34.14
    },
    {
      "low": 33.92,
      "Open": 33.93,
      "high": 34.2,
      "close": 34.16
    },
    {
      "low": 33.58,
      "Open": 33.61,
      "high": 33.82,
      "close": 33.77
    },
    {
      "low": 33.6249,
      "Open": 33.83,
      "high": 33.945,
      "close": 33.67
    },
    {
      "low": 33.5,
      "Open": 33.54,
      "high": 33.83,
      "close": 33.75
    },
    {
      "low": 33.45,
      "Open": 33.6,
      "high": 33.73,
      "close": 33.65
    },
    {
      "low": 33.11,
      "Open": 33.14,
      "high": 33.4,
      "close": 33.33
    },
    {
      "low": 32.575,
      "Open": 32.81,
      "high": 33.105,
      "close": 32.94
    },
    {
      "low": 33.83,
      "Open": 34.16,
      "high": 34.17,
      "close": 33.84
    },
    {
      "low": 33.683,
      "Open": 33.86,
      "high": 33.9653,
      "close": 33.83
    },
    {
      "low": 33.785,
      "Open": 33.85,
      "high": 34.32,
      "close": 34.22
    },
    {
      "low": 32.73,
      "Open": 32.74,
      "high": 33.37,
      "close": 33.26
    },
    {
      "low": 32.511,
      "Open": 33.02,
      "high": 33.175,
      "close": 32.57
    },
    {
      "low": 32.97,
      "Open": 33.1,
      "high": 33.42,
      "close": 33.38
    },
    {
      "low": 33.5,
      "Open": 33.86,
      "high": 33.88,
      "close": 33.51
    },
    {
      "low": 33.73,
      "Open": 33.87,
      "high": 34.175,
      "close": 34.11
    },
    {
      "low": 33.43,
      "Open": 33.62,
      "high": 33.78,
      "close": 33.77
    },
    {
      "low": 33.28,
      "Open": 33.46,
      "high": 33.69,
      "close": 33.51
    },
    {
      "low": 32.295,
      "Open": 32.46,
      "high": 32.66,
      "close": 32.66
    },
    {
      "low": 32.81,
      "Open": 32.85,
      "high": 32.9681,
      "close": 32.89
    },
    {
      "low": 32.405,
      "Open": 32.71,
      "high": 32.85,
      "close": 32.43
    },
    {
      "low": 32.94,
      "Open": 33.37,
      "high": 33.4,
      "close": 33.24
    },
    {
      "low": 33.175,
      "Open": 33.21,
      "high": 33.41,
      "close": 33.29
    },
    {
      "low": 32.93,
      "Open": 33.12,
      "high": 33.19,
      "close": 33.06
    },
    {
      "low": 32.59,
      "Open": 32.65,
      "high": 32.77,
      "close": 32.75
    },
    {
      "low": 32.435,
      "Open": 32.46,
      "high": 32.85,
      "close": 32.77
    },
    {
      "low": 32.245,
      "Open": 32.54,
      "high": 32.56,
      "close": 32.32
    },
    {
      "low": 32.19,
      "Open": 32.28,
      "high": 32.75,
      "close": 32.74
    },
    {
      "low": 32.455,
      "Open": 32.97,
      "high": 33.015,
      "close": 32.59
    },
    {
      "low": 33.07,
      "Open": 33.43,
      "high": 33.44,
      "close": 33.24
    },
    {
      "low": 33.15,
      "Open": 33.27,
      "high": 33.48,
      "close": 33.38
    },
    {
      "low": 32.59,
      "Open": 32.71,
      "high": 32.95,
      "close": 32.93
    },
    {
      "low": 31.56,
      "Open": 31.67,
      "high": 31.8,
      "close": 31.59
    },
    {
      "low": 31.42,
      "Open": 31.57,
      "high": 31.74,
      "close": 31.7
    },
    {
      "low": 31.65,
      "Open": 31.71,
      "high": 31.8171,
      "close": 31.77
    },
    {
      "low": 31.77,
      "Open": 31.78,
      "high": 32.095,
      "close": 32.08
    },
    {
      "low": 31.4,
      "Open": 31.58,
      "high": 31.6,
      "close": 31.58
    },
    {
      "low": 31.0839,
      "Open": 31.31,
      "high": 31.36,
      "close": 31.21
    },
    {
      "low": 31.14,
      "Open": 31.24,
      "high": 31.42,
      "close": 31.16
    },
    {
      "low": 30.74,
      "Open": 30.91,
      "high": 31.52,
      "close": 31.32
    },
    {
      "low": 30.425,
      "Open": 30.49,
      "high": 30.71,
      "close": 30.66
    },
    {
      "low": 30.3031,
      "Open": 30.41,
      "high": 30.57,
      "close": 30.47
    },
    {
      "low": 30.07,
      "Open": 30.09,
      "high": 30.31,
      "close": 30.22
    },
    {
      "low": 30.19,
      "Open": 30.29,
      "high": 30.49,
      "close": 30.32
    },
    {
      "low": 31.13,
      "Open": 31.18,
      "high": 31.59,
      "close": 31.59
    },
    {
      "low": 30.35,
      "Open": 30.68,
      "high": 31.105,
      "close": 31.08
    },
    {
      "low": 30.825,
      "Open": 30.99,
      "high": 31.11,
      "close": 30.85
    },
    {
      "low": 31.03,
      "Open": 31.52,
      "high": 31.66,
      "close": 31.03
    },
    {
      "low": 31.38,
      "Open": 31.41,
      "high": 31.75,
      "close": 31.56
    },
    {
      "low": 30.74,
      "Open": 30.88,
      "high": 31.455,
      "close": 31.36
    },
    {
      "low": 30.835,
      "Open": 31.11,
      "high": 31.3,
      "close": 30.85
    },
    {
      "low": 30.615,
      "Open": 30.73,
      "high": 31.04,
      "close": 31.02
    },
    {
      "low": 30.84,
      "Open": 31.05,
      "high": 31.08,
      "close": 30.92
    },
    {
      "low": 30.53,
      "Open": 30.73,
      "high": 31.165,
      "close": 31.1
    },
    {
      "low": 30.51,
      "Open": 30.53,
      "high": 30.79,
      "close": 30.79
    },
    {
      "low": 30.735,
      "Open": 30.83,
      "high": 31.14,
      "close": 30.89
    },
    {
      "low": 30.38,
      "Open": 30.55,
      "high": 30.765,
      "close": 30.72
    },
    {
      "low": 30.11,
      "Open": 30.19,
      "high": 30.5999,
      "close": 30.44
    },
    {
      "low": 29.87,
      "Open": 29.93,
      "high": 30.37,
      "close": 30.0
    },
    {
      "low": 28.93,
      "Open": 29.43,
      "high": 29.775,
      "close": 29.7
    },
    {
      "low": 28.66,
      "Open": 29.71,
      "high": 29.785,
      "close": 29.17
    },
    {
      "low": 29.37,
      "Open": 29.62,
      "high": 29.745,
      "close": 29.42
    },
    {
      "low": 29.54,
      "Open": 29.82,
      "high": 29.89,
      "close": 29.77
    },
    {
      "low": 29.23,
      "Open": 29.25,
      "high": 29.5,
      "close": 29.28
    },
    {
      "low": 28.72,
      "Open": 29.1,
      "high": 29.11,
      "close": 28.78
    },
    {
      "low": 29.18,
      "Open": 29.73,
      "high": 29.85,
      "close": 29.28
    },
    {
      "low": 29.22,
      "Open": 29.37,
      "high": 29.75,
      "close": 29.72
    },
    {
      "low": 28.615,
      "Open": 29.01,
      "high": 29.3,
      "close": 29.29
    },
    {
      "low": 29.77,
      "Open": 29.92,
      "high": 30.11,
      "close": 29.78
    },
    {
      "low": 29.87,
      "Open": 29.9,
      "high": 30.34,
      "close": 30.14
    },
    {
      "low": 29.38,
      "Open": 29.51,
      "high": 29.77,
      "close": 29.68
    },
    {
      "low": 29.19,
      "Open": 29.52,
      "high": 29.6,
      "close": 29.37
    },
    {
      "low": 29.69,
      "Open": 29.71,
      "high": 30.02,
      "close": 29.74
    },
    {
      "low": 29.23,
      "Open": 29.27,
      "high": 29.55,
      "close": 29.52
    },
    {
      "low": 29.02,
      "Open": 29.31,
      "high": 29.405,
      "close": 29.26
    },
    {
      "low": 28.99,
      "Open": 29.33,
      "high": 29.38,
      "close": 29.18
    },
    {
      "low": 29.18,
      "Open": 29.22,
      "high": 29.42,
      "close": 29.34
    },
    {
      "low": 28.9,
      "Open": 29.32,
      "high": 29.385,
      "close": 29.08
    },
    {
      "low": 28.7,
      "Open": 28.9,
      "high": 28.99,
      "close": 28.82
    },
    {
      "low": 28.755,
      "Open": 29.11,
      "high": 29.13,
      "close": 29.02
    },
    {
      "low": 30.385,
      "Open": 30.46,
      "high": 30.64,
      "close": 30.56
    },
    {
      "low": 30.12,
      "Open": 30.16,
      "high": 30.515,
      "close": 30.47
    }
  ]
}

In [93]:
#2nd question
company_name='"ABB"'
query="SELECT dates , close-Open AS 'DIFFERENCE' FROM shares WHERE company_name=" + company_name
df=pd.read_sql_query(query,conn)
df.head(3)

        dates  DIFFERENCE
0  2021-06-24        0.51
1  2021-06-23       -0.30
2  2021-06-22        0.19

In [21]:
#3rd Question
def getAverage(conn):
    query="SELECT dates ,avg(close-Open) AS 'AVG' FROM shares GROUP BY dates"
    df=pd.read_sql_query(query,conn)
    return df
getAverage(conn)

         dates   AVG
0   2021-02-02  0.31
1   2021-02-03  0.10
2   2021-02-04 -0.09
3   2021-02-05 -0.08
4   2021-02-08 -0.24
..         ...   ...
95  2021-06-18 -0.26
96  2021-06-21  0.38
97  2021-06-22  0.19
98  2021-06-23 -0.30
99  2021-06-24  0.51

[100 rows x 2 columns]

In [17]:
#driver statement 
database=r"C:\Users\saksham.gupta\sqlite\db\pythonsqlite.db"
conn=sqlite3.connect(database)
cursor=conn.cursor()

In [19]:
#4th question
# function which will return maximum number of continuous days where closing value was greater 
# than opening value(where trend is positive) for a given company.
company_name='"ABB"'
def MaximumCount(conn,company_name):
    cursor=conn.cursor()
    query="SELECT Open , close FROM shares WHERE company_name=" + company_name
    #df=pd.read_sql_query(query,conn) for dataframe 
    res=cursor.execute(query)
    temp=[dict(zip([key[0] for key in cursor.description],row) for row in res)]
    return getMax(temp)

In [5]:
temp=[dict(zip([key[0] for key in cursor.description],row) for row in res)]

In [18]:
def getMax(temp):
    Max=0
    currMax=0
    for key in temp:
        for op,cl in key.items():
            if op[1]>cl[1]:
                Max=max(Max,currMax)
                currMax=0
            else:
                currMax+=1
    return f"The number of continuous records are {Max}"

In [20]:
company_name='"ABB"'
MaximumCount(conn,company_name)

The number of continuous records are 7

In [ ]:
#file exists and overwriting 
 if not file.exists():
        df.to_csv(filename+'.csv',columns=labels, index=False)
    else:
        with open(filename +'.csv', 'rw+') as f: # file would be created if not exists
            try:
                f.write()
    except:
        return False
return True
        
        
    try
    file=pathlib.Path.cwd().joinpath(filename+'.csv')

In [1]:
file=pathlib.Path.cwd().joinpath('testing .ipynb')
print(file)
if file.exists():
    print(True)

NameError: name 'pathlib' is not defined